### ISSUE TITLE
Placeholders... Placeholders everywhere...

### ISSUE THREAD

**Issue by lIIlIIlIIl** [CaptainNoBeard/Dududarude#6]
As far as I can tell, you have the modules ready; just not implemented. That would be a good thing to get on top of.

**Comment by CaptainNoBeard** [comment]
We want to fix the modules themselves before we integrate them with the website, as we found some bugs.

**Comment by XXX-WhatIsLife-XXX** [comment]
This isn't really an issue anyway, it's just progress. We have to get placeholders working first, just to make sure that the website works,
